### ISSUE TITLE
Still working? Not for me. 

### ISSUE THREAD

**Issue by ejlamarque** [capuccino26/MacroTrends-Scraping#1]
Hi Capuccino26, Could it be that it is not working anymore? There seem to have been some changes on Macrotrend and the scraper stopped working. Thank you.

**Comment by capuccino26** [comment]
Hello, haven't used this script for a long time, will try it ASAP and come back to you.

**Comment by capuccino26** [comment]
Hello, the script was fixed and is working again. Thanks for letting me know.

**Comment by ejlamarque** [comment]
Thank you for your quick response!. Really appreciate It. I will try it
this evening and let you know how it goes from my side. Thanks again.
