### ISSUE TITLE
Data conversion

### ISSUE THREAD

**Issue by michaelm75** [capuccino26/MacroTrends-Scraping#2]
Hi,
1'st of all great job, the code works and saves a lot of time.
I have encountered one issue. My excel is in th German version and my decimals split is done by comma (,). This leads to wrong values.
Is there any cance getting an converter build in? 
Thanks!

BR
MM

**Comment by capuccino26** [comment]
Hello,
Thanks for the feedback, just tested here and there is actually an error wih the script dealing with decimals, I will look into it as soon as possible.

Best Regards.

**Comment by michaelm75** [comment]
Perfect, thanks for responding.Please let me know when there are any news.BRMichaelVon meinem iPhone gesendetAm 02.05.2024 um 14:20 schrieb Pedro Carvalho ***@***.***>:﻿
Hello,
Thanks for the feedback, just tested here and there is actually an error wih the script dealing with decimals, I will look into it as soon as possible.
Best Regards.

**Comment by capuccino26** [comment]
Hello,

The script is fixed now, decimals are properly represented. Thanks for bringing it to my attention.

Best Regards.
